# ============================================================================
# Build and deploy MediaFix into a client instance.
#
# RULE: only mediafix-* files are written. No other mod or config is touched.
#   mods\mediafix-<version>.jar   <- our mod (FFmpeg natives are bundled inside it)
# The natives zip is no longer deployed separately: it lives inside the mod jar and
# the mod extracts it to <instance>\mediafix-ffmpeg\v2-bundled-... on first launch.
# The mediafix-*.json files under the instance root are the player's own
# settings, generated by the game; this script never overwrites them.
#
# Usage:
#   .\deploy.ps1
#   .\deploy.ps1 -Instance "D:\some\instance"
#   .\deploy.ps1 -SkipBuild
# ============================================================================
param(
    [string]$Instance = 'F:\potato world\.minecraft\versions\Potato World 26.9.17',
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $MyInvocation.MyCommand.Path

if (-not (Test-Path -LiteralPath $Instance)) {
    throw "Instance folder not found: $Instance"
}

if (-not $SkipBuild) {
    Write-Host '[build] gradlew build ...'
    & (Join-Path $repo 'gradlew.bat') build --console=plain -q
    if ($LASTEXITCODE -ne 0) { throw "Build failed (exit $LASTEXITCODE)" }
}

# 取【最新】的那个 jar：build/libs 里可能同时留着旧版本的 jar
$srcJar = Get-ChildItem (Join-Path $repo 'build\libs') -Filter 'mediafix-*.jar' |
          Where-Object { $_.Name -notmatch 'sources|javadoc|withStub|noStub' } |
          Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $srcJar) { throw 'mediafix-*.jar not found in build/libs' }
$srcNatives = Get-ChildItem (Join-Path $repo 'build\libs') -Filter 'mediafix-ffmpeg-natives-*.zip' | Select-Object -First 1

$running = @(Get-Process java -ErrorAction SilentlyContinue).Count
if ($running -gt 0) {
    Write-Host "[warn] $running java process(es) running - restart the game for changes to take effect." -ForegroundColor Yellow
}

$modsDir = Join-Path $Instance 'mods'
New-Item -ItemType Directory -Path $modsDir -Force | Out-Null

# Two jars with the same mod id make the game refuse to start: drop our older
# mediafix jars first (only files starting with mediafix- and ending in .jar).
Get-ChildItem $modsDir -File -Filter 'mediafix-*.jar' | ForEach-Object {
    if ($_.Name -ne $srcJar.Name) {
        Remove-Item $_.FullName -Force
        Write-Host "[clean] removed stale $($_.Name)"
    }
}

$dstJar = Join-Path $modsDir $srcJar.Name
Copy-Item $srcJar.FullName $dstJar -Force
$kb = [math]::Round($srcJar.Length / 1KB)
Write-Host "[deploy] $($srcJar.Name) -> mods\  ($kb KB)"

# Natives are bundled in the jar now. Remove the old separately-deployed copy and
# the directory it was extracted to, so we do not keep ~60MB of duplicate DLLs around.
$oldNatives = @()
$oldNatives += Get-ChildItem (Join-Path $Instance 'config\mediafix\natives') -File -Filter 'mediafix-ffmpeg-natives-*.zip' -ErrorAction SilentlyContinue
$oldNatives += Get-ChildItem $modsDir -File -Filter 'mediafix-ffmpeg-natives-*.zip' -ErrorAction SilentlyContinue
foreach ($f in $oldNatives) {
    Remove-Item $f.FullName -Force
    Write-Host "[clean] removed the separately deployed $($f.Name) (now bundled in the jar)"
}
$oldExtract = Get-ChildItem (Join-Path $Instance 'mediafix-ffmpeg') -Directory -ErrorAction SilentlyContinue |
              Where-Object { $_.Name -like 'v2-mediafix-ffmpeg-natives*' }
foreach ($d in $oldExtract) {
    Remove-Item $d.FullName -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "[clean] removed the old extracted natives folder $($d.Name)"
}
if ($srcNatives) {
    $mb = [math]::Round($srcNatives.Length / 1MB, 1)
    Write-Host "[note] natives ($mb MB) are bundled in the jar; nothing separate to copy"
}

Write-Host ''
Write-Host '=== mediafix files in the instance ==='
Get-ChildItem $modsDir -File | Where-Object { $_.Name -match '^mediafix' } |
    Select-Object Name, @{n='KB';e={[math]::Round($_.Length / 1KB)}} |
    Format-Table -AutoSize | Out-String -Width 120 | Write-Host
Write-Host '[done] no other mod was modified.'
